# Generated by Django 4.1.3 on 2022-12-18 07:02

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheetapp', '0005_company_user_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Downtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('starttime', models.CharField(blank=True, max_length=100, null=True)),
                ('endtime', models.CharField(blank=True, max_length=100, null=True)),
                ('cycletime', models.CharField(blank=True, max_length=100, null=True)),
                ('operator', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, default=list, null=True, size=None)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sheetapp.machine')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sheetapp.order')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sheetapp.process')),
            ],
        ),
    ]
